### ISSUE TITLE
changing width on layer: traceback on _postgis_query key

### ISSUE THREAD

**Issue by grahame** [ealgis/ealgis#80]
```
web_1        | Traceback (most recent call last):
web_1        |   File "/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1        |     response = get_response(request)
web_1        |   File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1        |     response = self.process_exception_by_middleware(e, request)
web_1        |   File "/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1        |   File "/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
web_1        |     return view_func(*args, **kwargs)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 83, in view
web_1        |     return self.dispatch(request, *args, **kwargs)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
web_1        |     response = self.handle_exception(exc)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
web_1        |     self.raise_uncaught_exception(exc)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
web_1        |     response = handler(request, *args, **kwargs)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 70, in update
web_1        |     self.perform_update(serializer)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 80, in perform_update
web_1        |     serializer.save()
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 209, in save
web_1        |     self.instance = self.update(self.instance, validated_data)
web_1        |   File "/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 945, in update
web_1        |     instance.save()
web_1        |   File "/env/lib/python3.6/site-packages/django/db/models/base.py", line 806, in save
web_1        |     force_update=force_update, update_fields=update_fields)
web_1        |   File "/env/lib/python3.6/site-packages/django/db/models/base.py", line 831, in save_base
web_1        |     update_fields=update_fields,
web_1        |   File "/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in send
web_1        |     for receiver in self._live_receivers(sender)
web_1        |   File "/env/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 193, in <listcomp>
web_1        |     for receiver in self._live_receivers(sender)
web_1        |   File "/app/ealgis/ealauth/signals.py", line 12, in pre_save_map
web_1        |     instance.set(instance.json)
web_1        |   File "/app/ealgis/ealauth/models.py", line 152, in set
web_1        |     return self._set(defn, **kwargs)
web_1        |   File "/app/ealgis/ealauth/models.py", line 146, in _set
web_1        |     self._layer_set_latlon_bbox(layer, self._get_latlon_bbox(layer))
web_1        |   File "/app/ealgis/ealauth/models.py", line 120, in _get_latlon_bbox
web_1        |     """.format(query=layer['_postgis_query'])
web_1        | KeyError: '_postgis_query'
```

**Comment by grahame** [comment]
Closing as not a bug - just a migration issue between dev versions.
